services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
      - go-cache:/go
      - type: bind
        source: ${HOME}/.gitconfig
        # root ユーザーから vscode ユーザーに変更
        target: /home/vscode/.gitconfig
      - type: bind
        source: ${HOME}/.ssh
        # root ユーザーから vscode ユーザーに変更
        target: /home/vscode/.ssh
      # Docker ソケットのマウントを追加
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    command: sleep infinity
    environment:
      - TZ=Asia/Tokyo
      - LANG=en_US.UTF-8
    # seccomp の設定を追加
    security_opt:
      - seccomp:unconfined
    network_mode: service:db
    # ユーザー設定を追加
    user: vscode

  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: devpassword
      MYSQL_DATABASE: devdb
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpassword
    volumes:
      - mysql-data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  redis:
    image: redis:alpine
    restart: unless-stopped
    network_mode: service:db

volumes:
  go-cache:
  mysql-data: